name: Build & Deploy Angular to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NG_APP_NAME: resume-builder
  BASE_HREF: /${{ github.event.repository.name }}/

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Build: we deploy the browser output only (static)
      - name: Build (Angular)
        run: |
          npm run build -- --configuration=production --base-href "${BASE_HREF}" --prerender || \
          npm run build -- --configuration=production --base-href "${BASE_HREF}"

      - name: Prepare static output (browser only)
        run: |
          DIST_DIR="dist/${NG_APP_NAME}/browser"
          if [ ! -d "$DIST_DIR" ]; then
            echo "Expected browser output at $DIST_DIR not found."
            echo "Build produced:"
            ls -la dist || true
            exit 1
          fi
          echo "Contents of $DIST_DIR:"
          ls -la "$DIST_DIR"

          # Prefer prerendered index.html; otherwise rename CSR entry
          if [ -f "$DIST_DIR/index.html" ]; then
            echo "Found prerendered index.html; using it."
          elif [ -f "$DIST_DIR/index.csr.html" ]; then
            echo "index.html not found; renaming index.csr.html -> index.html"
            mv "$DIST_DIR/index.csr.html" "$DIST_DIR/index.html"
          else
            echo "Neither index.html nor index.csr.html found in $DIST_DIR"
            exit 1
          fi

          # SPA deep-link fallback + disable Jekyll
          cp "$DIST_DIR/index.html" "$DIST_DIR/404.html"
          touch "$DIST_DIR/.nojekyll"

      # This will also ENABLE Pages if it's not already enabled
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload artifact (static site)
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/${{ env.NG_APP_NAME }}/browser

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
